config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :games, except: [:show] do
    resources :create, controller: 'games/setup'
    resources :participations, only: [:new]
    member do
      get "create/review", to: 'games/setup#review'
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'join_game', to: 'pages#join_game'
  get 'events', to: 'pages#events'
  # get 'participations/new'
  # get 'participations/create'
  get 'landing', to: 'pages#landing'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <!-- <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4"> -->
        <div class="footer-item">
          <%= image_tag "court_outline_footer.png", height: 70 %>
          <h1>Make your<br>tennis club<br>social again.</h1>
          <div class="footer-copyright">
          © by the clubhouse
          </div>
        </div>
<!--       </div> -->

<!--       <div class="col-xs-12 col-sm-6 col-md-4"> -->
        <div class="footer-item">
          <div class="list-footer">
            <ul>
              <li><%= link_to "JOIN GAME", join_game_path %></li>
              <li><%= link_to "GAMES", games_path %></li>
              <li><%= link_to "EVENTS", events_path %></li>
            </ul>
          </div>
        </div>
<!--       </div> -->
<!--       <div class="col-xs-12 col-sm-6 col-md-4"> -->
        <div class="footer-item">
          <div class="footer-address">
            <p><strong>All England Lawn Tennis Club</strong> <br>Church Rd, Wimbledon<br>London SW19 5AE <br>+43 2314 23412 <br>allengland@tennis.co.uk</p>
          </div>
          <div class="footer-links">
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
          </div>
        </div>
<!--       </div> -->
<!--     </div>
  </div> -->
</div>

app/views/shared/_navbar.html.erb
<!--  NAV CLUBHAUS -->


<div class = "nav-clubhaus">
  <% if user_signed_in? %>

  <!-- Links when logged in -->
  <div class="clubhaus-nav-left hidden-xs hidden-sm">
    <%= link_to "JOIN GAME", join_game_path, class: "nav-clubhaus-item nav-clubhaus-link" %>
    <%= link_to "WATCH GAME", games_path, class: "nav-clubhaus-item nav-clubhaus-link" %>
    <%= link_to "EVENTS", events_path, class: "nav-clubhaus-item nav-clubhaus-link" %>
  </div>

  <!-- Logo centered -->
  <div class="clubhaus-logo">
    <%= link_to root_path do %>
    <%= image_tag "logo_white_transp.png", height: 50 %>
    <% end %>
  </div>

  <div class="clubhaus-nav-right">
    <div class="dropdown">
      <%= image_tag "#{current_user.photo}", class: "avatar dropdown-toggle", id: "nav-clubhaus-menu", "data-toggle" => "dropdown" %>
      <ul class="dropdown-menu dropdown-menu-right nav-clubhaus-dropdown-menu">
        <li>
          <%= link_to user_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>

  <% else %>

    <!-- Logo -->
  <div class="clubhaus-logo">
    <%= link_to root_path do %>
    <%= image_tag "logo_white_transp.png", height: 50 %>
    <% end %>
  </div>

  <!-- Login link (when logged out) -->
  <div class="clubhaus-nav-left">
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "nav-clubhaus-item nav-clubhaus-link" %>
  </div>
    <!-- Dropdown list appearing on mobile only -->
  <% end %>
  <div class="nav-clubhaus-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-left nav-clubhaus-dropdown-menu">
        <li><%= link_to "JOIN GAME", join_game_path, class: "nav-clubhaus-item nav-clubhaus-link" %></li>
        <li><%= link_to "WATCH GAME", games_path, class: "nav-clubhaus-item nav-clubhaus-link" %></li>
        <li><%= link_to "EVENTS", events_path, class: "nav-clubhaus-item nav-clubhaus-link" %></li>
      </ul>
    </div>
  </div>

</div>

app/views/shared/_search_filters.html.erb
<div class="search-filters">
  <div class="btn-group">
    <%= link_to join_game_path(time: :time) do %>
      <input class="btn-prim" type="button" value="today">
    <% end %>
  </div>

  <div class="btn-group">
    <div class="dropdown">
      <button class="btn-prim dropdown-toggle" type="button" data-toggle="dropdown">skill-level
      <span class="caret"></span></button>
      <ul class="dropdown-menu">
        <li><%= link_to "ITN 1-3", join_game_path(skill_level: :'1') %></li>
        <li><%= link_to "ITN 3-3", join_game_path(skill_level: :'3') %></li>
        <li><%= link_to "ITN 6-9", join_game_path(skill_level: :'6') %></li>
      </ul>
    </div>
  </div>

  <div class="btn-group">
    <div class="dropdown">
    <button class="btn-prim dropdown-toggle" type="button" data-toggle="dropdown">game-type<span class="caret"></span>
    </button>
      <ul class="dropdown-menu">
        <li><%= link_to "Singles", join_game_path(game_type: :singles) %></li>
        <li><%= link_to "Doubles", join_game_path(game_type: :doubles) %></li>
      </ul>
    </div>
  </div>
</div>