config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :games, except: [:show] do
    resources :create, controller: 'games/setup'
    resources :participations, only: [:new]
    member do
      get "create/review", to: 'games/setup#review'
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'join_game', to: 'pages#join_game'
  get 'events', to: 'pages#events'
  # get 'participations/new'
  # get 'participations/create'
  get 'landing', to: 'pages#landing'
end

app/views/pages/_search_filters.html.erb
<div class="search-filters">
  <div class="btn-group">
    <%= link_to join_game_path(time: :time) do %>
        <input class="btn-sec" type="button" value="today">
    <% end %>
  </div>

  <div class="btn-group">
    <div class="dropdown">
      <button class="btn-sec dropdown-toggle" type="button" data-toggle="dropdown">skill-level
      <span class="caret"></span></button>
      <ul class="dropdown-menu">
        <li><%= link_to "ITN 1-3", games_path(skill_range: :'1-3') %></li>
        <li><%= link_to "ITN 3-6", games_path(skill_range: :'3-6') %></li>
        <li><%= link_to "ITN 6-9", games_path(skill_range: :'6-9') %></li>
      </ul>
    </div>
  </div>

  <div class="btn-group">
    <div class="dropdown">
    <button class="btn-sec dropdown-toggle" type="button" data-toggle="dropdown">game-type<span class="caret"></span>
    </button>
      <ul class="dropdown-menu">
        <li><%= link_to "Singles", join_game_path(game_type: :singles) %></li>
        <li><%= link_to "Doubles", join_game_path(game_type: :doubles) %></li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/events.html.erb
<h1>This is where our events will go</h1>

app/views/pages/home.html.erb
<!--WEATHER & NEWS BAR-->
<div class="info-bar">
  <div class="date">
    <p><%= Date.today.to_s(:long) %></p>
  </div>
  <div class="weather">
    <%= image_tag "cloud.png", height: 45 %>
  </div>
  <div class="weather">
    <p>22°C, mostly sunny</p>
  </div>
  <div class="court-info">
    <%= image_tag "tennis-court.png", height: 45 %>
  </div>
  <div class="court-info">
    <p>all courts open</p>
  </div>
</div>

<!--HELLO SECTION-->
<div class="hello-section">
  <% if Time.zone.now.hour >= 6.00 && Time.zone.now.hour <= 10.30 %>
    <h1>Good morning <%= current_user.first_name %>,</h1>
    <h2>another great day <br> to play tennis.</h2>
  <% elsif Time.zone.now.hour >= 10.31 && Time.zone.now.hour <= 16.30%>
    <h1>Hi <%= current_user.first_name %>,</h1>
    <h2>you could still <br> play tennis today.</h2>
  <% elsif Time.zone.now.hour >= 16.31 && Time.zone.now.hour <= 18.30%>
    <h1>Good evening <%= current_user.first_name %>,</h1>
    <h2>it might be a bit late today<br>but tomorrow is another great day to play.</h2>
  <% else %>
    <h1>Yo <%= current_user.first_name %>,</h1>
    <h2>Can't sleep? <br> Better go play tennis tomorrow.</h2>
  <% end %>
  <%= link_to "find a partner", games_path, method: :post, class: "btn-prim" %>
</div>

<!--TABS GAMES-->
<%= render 'tabs' %>

app/views/pages/join_game.html.erb
<!-- <div class="container">
  <div class="row"> -->
    <div class="search-container">
      <div id="header-link">
        <h2>Find a game that suits you.</h2>
        <%= link_to "find a partner", games_path, method: :post, class: "btn-prim" %>
      </div>

      <div class="search-filter-section">
        <div class="searchbar">

          <div class="input-group form">
            <%= form_tag(join_game_path, method: 'get') do %>
            <span class="top_search_icon"><%= image_tag "group.png" %></span>
              <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "search for name"%>
            <% end %>
          </div>
        </div>

        <!--SEARCH FILTERS-->
        <%= render 'search_filters' %>
      </div>

      <!--GAMES LIST-->
      <div class="games-list">
        <% @games.each do |game| %>
        <% @max_number_of_players = 2 if game.game_type == "Singles" %>
        <% @max_number_of_players = 4 if game.game_type == "Doubles" %>
        <div class="card-list" id="games-list" data-games = <%= @game %>>
          <div class="card-avatar">
              <div class="avatar-batch">
                <img class="avatar-large" alt="avatar" src="<%= game.host.photo %>" />
                <div class="skill-level-badge-position skill-level-badge">
                    <p><%= game.skill_level %></p>
                  <h5>itn</h5>
                </div>
                <div class="card-specifications">
                  <h3><%= game.game_type %></h3>
                  <h4><%= game.date.month %>.<%= game.date.day %>.<%= game.date.year %> at <%= game.time.hour %>h<%= game.time.min %></h4>
                  <h5>with <%= game.host.first_name %> <%= game.host.last_name %> </h5>
                </div>
              </div>
          </div>
          <div class="card-spots">
            <h4><%= game.participations.length %> / <%= @max_number_of_players %></h4>
          </div>
          <div>
            <% if game.host != current_user %>
            <%= link_to "Join", new_game_participation_path(game), class:"btn-prim-s"%>
            <% else %>
            <div style="width: 74px;"></div>
            <% end %>
          </div>
      </div>
        <% end %>
    </div>
<!--   </div>
</div> -->

app/views/pages/landing.html.erb
<div class="background-image">
  <div class="relative">
    <div class="flex-land">
      <div class="logo">
        <%= image_tag "logo_white_transp.png", height: 98 %>
      </div>
      <div>
        <h1 class="text-white">Play more tennis.</h1>
      </div>
      <div>
        <p class="text-white">Get your club social again <br> & connect your members to easily find partners</p>
      </div>
      <div class="buttons-landing">
      <%= link_to "Sign up", new_user_registration_path, {class: "btn-prim-land"} %>

      <%= link_to "Log in", new_user_session_path, {class: "btn-prim-land"} %>
      </div>
    </div>
  </div>
</div>

app/views/pages/uikit.html.erb
<!--HEADERS, TEXT, LINKS-->
<div class="container">
  <h1>This is an h1</h1>
  <h2>This is an h2</h2>
  <h3>This is an h3</h3>
  <h4>This is an h4</h4>
  <h5>This is an h5</h5>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam ut   veniam explicabo ipsa optio, vitae dolorum nisi vel libero laboriosam   nulla facilis dolor provident, non ipsam error ullam porro asperiores!</p>
  <a>a link</a>

<!--BUTTONS-->
  <a href="#" class="btn-prim">btn-prim</a>
  <a href="#" class="btn-sec">btn-sec</a>

  <a href="#" class="btn-prim-s">btn-prim-s</a>
  <a href="#" class="btn-sec-s">btn-sec-s</a>

<!--AVATARS-->
  <img class="avatar" alt="avatar" src="  https://www.fm1today.ch/2019/03/20190302172247798-640x640.jpg" />

  <img class="avatar-large" alt="avatar" src="  https://www.fm1today.ch/2019/03/20190302172247798-640x640.jpg" />

<!--CARD FOR LISTS-->
  <div class="card-list">
    <div class="card-avatar">
      <div class="avatar-batch">
        <img class="avatar-large" alt="avatar" src="https://www.fm1today.ch/2019/03/20190302172247798-640x640.jpg" />
        <div class="skill-level-badge-position skill-level-badge">
          <p>5-6</p>
          <h5>itn</h5>
        </div>
        <div class="card-specifications">
          <h3>Single</h3>
          <h4>19.5.2018 at 17h00</h4>
          <h5>with Dominik Thiem</h5>
        </div>
      </div>
    </div>
    <div class="card-spots">
      <h4>1 / 2</h4>
    </div>
    <div>
      <a href="#" class="btn-prim-s">join</a>
    </div>
  </div>

  <br>
  <br>
  <br>

<!--CARD COURTS-->

  <br>
  <br>
  <br>

  <div class="card-court">
    <div class="bottom-border"></div>

     <div class="court-date">
       <p>17.2.2019</p>
       <p>17h00</p>
     </div>

     <div class="court-player-left">
      <table>
        <tr>
          <td>
            <img class="avatar" alt="avatar" src="https://www.fm1today.ch/2019/03/20190302172247798-640x640.jpg"/>
          </td>
          <td>
            <p>Roger<br>Federer</p>
          </td>
        </tr>
        <tr>
          <td>
            <img class="avatar" alt="avatar" src="       https://www.fm1today.ch/2019/03/20190302172247798-640x640.jpg"/>
          </td>
          <td>
            <p>Roger<br>Federer</p>
          </td>
        </tr>
      </table>
     </div>

     <div class="skill-level-badge skill-level-position">
       <p>5-6</p>
       <h5>itn</h5>
     </div>

     <div class="court-player-right">
      <table>
        <tr>
          <td>
            <img class="avatar" alt="avatar" src="https://www.fm1today.ch/2019/03/20190302172247798-640x640.jpg"/>
          </td>
          <td>
            <p>Roger<br>Federer</p>
          </td>
        </tr>
        <tr>
          <td>
            <img class="avatar" alt="avatar" src="https://www.fm1today.ch/2019/03/20190302172247798-640x640.jpg"/>
          </td>
          <td>
            <p>Roger<br>Federer</p>
          </td>
        </tr>
      </table>
     </div>
  </div>

</div>